#include "DboInstaller.h"

namespace WW
{
	namespace Installer
	{

void DboInstaller::insertLanguages()
{
	//English
	auto englishLanguage = new Dbo::Language("en");
	englishLanguage->name = "English";
	englishLanguage->nativeName = "English";
	englishLanguage->languageAccept = "en*";
	englishLanguage->pluralExpression = "n > 1 ? 1 : 0"; //Case 0 for Singular string and Case 1 for Plural string
	englishLanguage->pluralCases = 2;
	englishLanguage->installed = true;
	O.EnglishLanguage = dboSession.add(englishLanguage);

	//Basic formatting strings
	addSingularKeyString(O.EnglishLanguage, "DecimalPointCharacter", O.LocalizationModule, ".");
	addSingularKeyString(O.EnglishLanguage, "NumberThousandSeparator", O.LocalizationModule, ",");
	addSingularKeyString(O.EnglishLanguage, "DateFormat", O.LocalizationModule, "MMMM dd, yyyy");

	//Un installed languages
	dboSession.add(new Dbo::Language("ab", "Abkhaz", "", "ab*", "", -1, false));
	dboSession.add(new Dbo::Language("aa", "Afar", "", "aa*", "", -1, false));
	dboSession.add(new Dbo::Language("af", "Afrikaans", "", "af*", "", -1, false));
	dboSession.add(new Dbo::Language("ak", "Akan", "", "ak*", "", -1, false));
	dboSession.add(new Dbo::Language("sq", "Albanian", "", "sq*", "", -1, false));
	dboSession.add(new Dbo::Language("am", "Amharic", "", "am*", "", -1, false));
	dboSession.add(new Dbo::Language("ar", "Arabic", "", "ar*", "", -1, false));
	dboSession.add(new Dbo::Language("an", "Aragonese", "", "an*", "", -1, false));
	dboSession.add(new Dbo::Language("hy", "Armenian", "", "hy*", "", -1, false));
	dboSession.add(new Dbo::Language("as", "Assamese", "", "as*", "", -1, false));
	dboSession.add(new Dbo::Language("av", "Avaric", "", "av*", "", -1, false));
	dboSession.add(new Dbo::Language("ae", "Avestan", "", "ae*", "", -1, false));
	dboSession.add(new Dbo::Language("ay", "Aymara", "", "ay*", "", -1, false));
	dboSession.add(new Dbo::Language("az", "Azerbaijani", "", "az*", "", -1, false));
	dboSession.add(new Dbo::Language("bm", "Bambara", "", "bm*", "", -1, false));
	dboSession.add(new Dbo::Language("ba", "Bashkir", "", "ba*", "", -1, false));
	dboSession.add(new Dbo::Language("eu", "Basque", "", "eu*", "", -1, false));
	dboSession.add(new Dbo::Language("be", "Belarusian", "", "be*", "", -1, false));
	dboSession.add(new Dbo::Language("bn", "Bengali; Bangla", "", "bn*", "", -1, false));
	dboSession.add(new Dbo::Language("bh", "Bihari", "", "bh*", "", -1, false));
	dboSession.add(new Dbo::Language("bi", "Bislama", "", "bi*", "", -1, false));
	dboSession.add(new Dbo::Language("bs", "Bosnian", "", "bs*", "", -1, false));
	dboSession.add(new Dbo::Language("br", "Breton", "", "br*", "", -1, false));
	dboSession.add(new Dbo::Language("bg", "Bulgarian", "", "bg*", "", -1, false));
	dboSession.add(new Dbo::Language("my", "Burmese", "", "my*", "", -1, false));
	dboSession.add(new Dbo::Language("ca", "Catalan; Valencian", "", "ca*", "", -1, false));
	dboSession.add(new Dbo::Language("ch", "Chamorro", "", "ch*", "", -1, false));
	dboSession.add(new Dbo::Language("ce", "Chechen", "", "ce*", "", -1, false));
	dboSession.add(new Dbo::Language("ny", "Chichewa; Chewa; Nyanja", "", "ny*", "", -1, false));
	dboSession.add(new Dbo::Language("zh", "Chinese", "", "zh*", "", -1, false));
	dboSession.add(new Dbo::Language("cv", "Chuvash", "", "cv*", "", -1, false));
	dboSession.add(new Dbo::Language("kw", "Cornish", "", "kw*", "", -1, false));
	dboSession.add(new Dbo::Language("co", "Corsican", "", "co*", "", -1, false));
	dboSession.add(new Dbo::Language("cr", "Cree", "", "cr*", "", -1, false));
	dboSession.add(new Dbo::Language("hr", "Croatian", "", "hr*", "", -1, false));
	dboSession.add(new Dbo::Language("cs", "Czech", "", "cs*", "", -1, false));
	dboSession.add(new Dbo::Language("da", "Danish", "", "da*", "", -1, false));
	dboSession.add(new Dbo::Language("dv", "Divehi; Dhivehi; Maldivian;", "", "dv*", "", -1, false));
	dboSession.add(new Dbo::Language("nl", "Dutch", "", "nl*", "", -1, false));
	dboSession.add(new Dbo::Language("dz", "Dzongkha", "", "dz*", "", -1, false));
	dboSession.add(new Dbo::Language("eo", "Esperanto", "", "eo*", "", -1, false));
	dboSession.add(new Dbo::Language("et", "Estonian", "", "et*", "", -1, false));
	dboSession.add(new Dbo::Language("ee", "Ewe", "", "ee*", "", -1, false));
	dboSession.add(new Dbo::Language("fo", "Faroese", "", "fo*", "", -1, false));
	dboSession.add(new Dbo::Language("fj", "Fijian", "", "fj*", "", -1, false));
	dboSession.add(new Dbo::Language("fi", "Finnish", "", "fi*", "", -1, false));
	O.FrenchLanguage = dboSession.add(new Dbo::Language("fr", "French", "", "fr*", "", -1, false));
	dboSession.add(new Dbo::Language("ff", "Fula; Fulah; Pulaar; Pular", "", "ff*", "", -1, false));
	dboSession.add(new Dbo::Language("gl", "Galician", "", "gl*", "", -1, false));
	dboSession.add(new Dbo::Language("ka", "Georgian", "", "ka*", "", -1, false));
	dboSession.add(new Dbo::Language("de", "German", "", "de*", "", -1, false));
	dboSession.add(new Dbo::Language("el", "Greek, Modern", "", "el*", "", -1, false));
	dboSession.add(new Dbo::Language("gn", "Guaraní", "", "gn*", "", -1, false));
	dboSession.add(new Dbo::Language("gu", "Gujarati", "", "gu*", "", -1, false));
	dboSession.add(new Dbo::Language("ht", "Haitian; Haitian Creole", "", "ht*", "", -1, false));
	dboSession.add(new Dbo::Language("ha", "Hausa", "", "ha*", "", -1, false));
	dboSession.add(new Dbo::Language("he", "Hebrew (modern)", "", "he*", "", -1, false));
	dboSession.add(new Dbo::Language("hz", "Herero", "", "hz*", "", -1, false));
	dboSession.add(new Dbo::Language("hi", "Hindi", "", "hi*", "", -1, false));
	dboSession.add(new Dbo::Language("ho", "Hiri Motu", "", "ho*", "", -1, false));
	dboSession.add(new Dbo::Language("hu", "Hungarian", "", "hu*", "", -1, false));
	dboSession.add(new Dbo::Language("ia", "Interlingua", "", "ia*", "", -1, false));
	dboSession.add(new Dbo::Language("id", "Indonesian", "", "id*", "", -1, false));
	dboSession.add(new Dbo::Language("ie", "Interlingue", "", "ie*", "", -1, false));
	dboSession.add(new Dbo::Language("ga", "Irish", "", "ga*", "", -1, false));
	dboSession.add(new Dbo::Language("ig", "Igbo", "", "ig*", "", -1, false));
	dboSession.add(new Dbo::Language("ik", "Inupiaq", "", "ik*", "", -1, false));
	dboSession.add(new Dbo::Language("io", "Ido", "", "io*", "", -1, false));
	dboSession.add(new Dbo::Language("is", "Icelandic", "", "is*", "", -1, false));
	dboSession.add(new Dbo::Language("it", "Italian", "", "it*", "", -1, false));
	dboSession.add(new Dbo::Language("iu", "Inuktitut", "", "iu*", "", -1, false));
	dboSession.add(new Dbo::Language("ja", "Japanese", "", "ja*", "", -1, false));
	dboSession.add(new Dbo::Language("jv", "Javanese", "", "jv*", "", -1, false));
	dboSession.add(new Dbo::Language("kl", "Kalaallisut, Greenlandic", "", "kl*", "", -1, false));
	dboSession.add(new Dbo::Language("kn", "Kannada", "", "kn*", "", -1, false));
	dboSession.add(new Dbo::Language("kr", "Kanuri", "", "kr*", "", -1, false));
	dboSession.add(new Dbo::Language("ks", "Kashmiri", "", "ks*", "", -1, false));
	dboSession.add(new Dbo::Language("kk", "Kazakh", "", "kk*", "", -1, false));
	dboSession.add(new Dbo::Language("km", "Khmer", "", "km*", "", -1, false));
	dboSession.add(new Dbo::Language("ki", "Kikuyu, Gikuyu", "", "ki*", "", -1, false));
	dboSession.add(new Dbo::Language("rw", "Kinyarwanda", "", "rw*", "", -1, false));
	dboSession.add(new Dbo::Language("ky", "Kyrgyz", "", "ky*", "", -1, false));
	dboSession.add(new Dbo::Language("kv", "Komi", "", "kv*", "", -1, false));
	dboSession.add(new Dbo::Language("kg", "Kongo", "", "kg*", "", -1, false));
	dboSession.add(new Dbo::Language("ko", "Korean", "", "ko*", "", -1, false));
	dboSession.add(new Dbo::Language("ku", "Kurdish", "", "ku*", "", -1, false));
	dboSession.add(new Dbo::Language("kj", "Kwanyama, Kuanyama", "", "kj*", "", -1, false));
	dboSession.add(new Dbo::Language("la", "Latin", "", "la*", "", -1, false));
	dboSession.add(new Dbo::Language("lb", "Luxembourgish, Letzeburgesch", "", "lb*", "", -1, false));
	dboSession.add(new Dbo::Language("lg", "Ganda", "", "lg*", "", -1, false));
	dboSession.add(new Dbo::Language("li", "Limburgish, Limburgan, Limburger", "", "li*", "", -1, false));
	dboSession.add(new Dbo::Language("ln", "Lingala", "", "ln*", "", -1, false));
	dboSession.add(new Dbo::Language("lo", "Lao", "", "lo*", "", -1, false));
	dboSession.add(new Dbo::Language("lt", "Lithuanian", "", "lt*", "", -1, false));
	dboSession.add(new Dbo::Language("lu", "Luba-Katanga", "", "lu*", "", -1, false));
	dboSession.add(new Dbo::Language("lv", "Latvian", "", "lv*", "", -1, false));
	dboSession.add(new Dbo::Language("gv", "Manx", "", "gv*", "", -1, false));
	dboSession.add(new Dbo::Language("mk", "Macedonian", "", "mk*", "", -1, false));
	dboSession.add(new Dbo::Language("mg", "Malagasy", "", "mg*", "", -1, false));
	dboSession.add(new Dbo::Language("ms", "Malay", "", "ms*", "", -1, false));
	dboSession.add(new Dbo::Language("ml", "Malayalam", "", "ml*", "", -1, false));
	dboSession.add(new Dbo::Language("mt", "Maltese", "", "mt*", "", -1, false));
	dboSession.add(new Dbo::Language("mi", "Maori", "", "mi*", "", -1, false));
	dboSession.add(new Dbo::Language("mr", "Marathi", "", "mr*", "", -1, false));
	dboSession.add(new Dbo::Language("mh", "Marshallese", "", "mh*", "", -1, false));
	dboSession.add(new Dbo::Language("mn", "Mongolian", "", "mn*", "", -1, false));
	dboSession.add(new Dbo::Language("na", "Nauru", "", "na*", "", -1, false));
	dboSession.add(new Dbo::Language("nv", "Navajo, Navaho", "", "nv*", "", -1, false));
	dboSession.add(new Dbo::Language("nb", "Norwegian Bokmål", "", "nb*", "", -1, false));
	dboSession.add(new Dbo::Language("nd", "North Ndebele", "", "nd*", "", -1, false));
	dboSession.add(new Dbo::Language("ne", "Nepali", "", "ne*", "", -1, false));
	dboSession.add(new Dbo::Language("ng", "Ndonga", "", "ng*", "", -1, false));
	dboSession.add(new Dbo::Language("nn", "Norwegian Nynorsk", "", "nn*", "", -1, false));
	dboSession.add(new Dbo::Language("no", "Norwegian", "", "no*", "", -1, false));
	dboSession.add(new Dbo::Language("ii", "Nuosu", "", "ii*", "", -1, false));
	dboSession.add(new Dbo::Language("nr", "South Ndebele", "", "nr*", "", -1, false));
	dboSession.add(new Dbo::Language("oc", "Occitan", "", "oc*", "", -1, false));
	dboSession.add(new Dbo::Language("oj", "Ojibwe, Ojibwa", "", "oj*", "", -1, false));
	dboSession.add(new Dbo::Language("cu", "Old Church Slavonic", "", "cu*", "", -1, false));
	dboSession.add(new Dbo::Language("om", "Oromo", "", "om*", "", -1, false));
	dboSession.add(new Dbo::Language("or", "Oriya", "", "or*", "", -1, false));
	dboSession.add(new Dbo::Language("os", "Ossetian, Ossetic", "", "os*", "", -1, false));
	dboSession.add(new Dbo::Language("pa", "Panjabi, Punjabi", "", "pa*", "", -1, false));
	dboSession.add(new Dbo::Language("pi", "Pali", "", "pi*", "", -1, false));
	dboSession.add(new Dbo::Language("fa", "Persian (Farsi)", "", "fa*", "", -1, false));
	dboSession.add(new Dbo::Language("pl", "Polish", "", "pl*", "", -1, false));
	dboSession.add(new Dbo::Language("ps", "Pashto, Pushto", "", "ps*", "", -1, false));
	dboSession.add(new Dbo::Language("pt", "Portuguese", "", "pt*", "", -1, false));
	dboSession.add(new Dbo::Language("qu", "Quechua", "", "qu*", "", -1, false));
	dboSession.add(new Dbo::Language("rm", "Romansh", "", "rm*", "", -1, false));
	dboSession.add(new Dbo::Language("rn", "Kirundi", "", "rn*", "", -1, false));
	dboSession.add(new Dbo::Language("ro", "Romanian, [])", "", "ro*", "", -1, false));
	dboSession.add(new Dbo::Language("ru", "Russian", "", "ru*", "", -1, false));
	dboSession.add(new Dbo::Language("sa", "Sanskrit (Samskrta)", "", "sa*", "", -1, false));
	dboSession.add(new Dbo::Language("sc", "Sardinian", "", "sc*", "", -1, false));
	dboSession.add(new Dbo::Language("sd", "Sindhi", "", "sd*", "", -1, false));
	dboSession.add(new Dbo::Language("se", "Northern Sami", "", "se*", "", -1, false));
	dboSession.add(new Dbo::Language("sm", "Samoan", "", "sm*", "", -1, false));
	dboSession.add(new Dbo::Language("sg", "Sango", "", "sg*", "", -1, false));
	dboSession.add(new Dbo::Language("sr", "Serbian", "", "sr*", "", -1, false));
	dboSession.add(new Dbo::Language("gd", "Scottish Gaelic; Gaelic", "", "gd*", "", -1, false));
	dboSession.add(new Dbo::Language("sn", "Shona", "", "sn*", "", -1, false));
	dboSession.add(new Dbo::Language("si", "Sinhala, Sinhalese", "", "si*", "", -1, false));
	dboSession.add(new Dbo::Language("sk", "Slovak", "", "sk*", "", -1, false));
	dboSession.add(new Dbo::Language("sl", "Slovene", "", "sl*", "", -1, false));
	dboSession.add(new Dbo::Language("so", "Somali", "", "so*", "", -1, false));
	dboSession.add(new Dbo::Language("st", "Southern Sotho", "", "st*", "", -1, false));
	dboSession.add(new Dbo::Language("es", "Spanish; Castilian", "", "es*", "", -1, false));
	dboSession.add(new Dbo::Language("su", "Sundanese", "", "su*", "", -1, false));
	dboSession.add(new Dbo::Language("sw", "Swahili", "", "sw*", "", -1, false));
	dboSession.add(new Dbo::Language("ss", "Swati", "", "ss*", "", -1, false));
	dboSession.add(new Dbo::Language("sv", "Swedish", "", "sv*", "", -1, false));
	dboSession.add(new Dbo::Language("ta", "Tamil", "", "ta*", "", -1, false));
	dboSession.add(new Dbo::Language("te", "Telugu", "", "te*", "", -1, false));
	dboSession.add(new Dbo::Language("tg", "Tajik", "", "tg*", "", -1, false));
	dboSession.add(new Dbo::Language("th", "Thai", "", "th*", "", -1, false));
	dboSession.add(new Dbo::Language("ti", "Tigrinya", "", "ti*", "", -1, false));
	dboSession.add(new Dbo::Language("bo", "Tibetan Standard, Tibetan, Central", "", "bo*", "", -1, false));
	dboSession.add(new Dbo::Language("tk", "Turkmen", "", "tk*", "", -1, false));
	dboSession.add(new Dbo::Language("tl", "Tagalog", "", "tl*", "", -1, false));
	dboSession.add(new Dbo::Language("tn", "Tswana", "", "tn*", "", -1, false));
	dboSession.add(new Dbo::Language("to", "Tonga (Tonga Islands)", "", "to*", "", -1, false));
	dboSession.add(new Dbo::Language("tr", "Turkish", "", "tr*", "", -1, false));
	dboSession.add(new Dbo::Language("ts", "Tsonga", "", "ts*", "", -1, false));
	dboSession.add(new Dbo::Language("tt", "Tatar", "", "tt*", "", -1, false));
	dboSession.add(new Dbo::Language("tw", "Twi", "", "tw*", "", -1, false));
	dboSession.add(new Dbo::Language("ty", "Tahitian", "", "ty*", "", -1, false));
	dboSession.add(new Dbo::Language("ug", "Uyghur, Uighur", "", "ug*", "", -1, false));
	dboSession.add(new Dbo::Language("uk", "Ukrainian", "", "uk*", "", -1, false));
	dboSession.add(new Dbo::Language("ur", "Urdu", "", "ur*", "", -1, false));
	dboSession.add(new Dbo::Language("uz", "Uzbek", "", "uz*", "", -1, false));
	dboSession.add(new Dbo::Language("ve", "Venda", "", "ve*", "", -1, false));
	dboSession.add(new Dbo::Language("vi", "Vietnamese", "", "vi*", "", -1, false));
	dboSession.add(new Dbo::Language("vo", "Volapük", "", "vo*", "", -1, false));
	dboSession.add(new Dbo::Language("wa", "Walloon", "", "wa*", "", -1, false));
	dboSession.add(new Dbo::Language("cy", "Welsh", "", "cy*", "", -1, false));
	dboSession.add(new Dbo::Language("wo", "Wolof", "", "wo*", "", -1, false));
	dboSession.add(new Dbo::Language("fy", "Western Frisian", "", "fy*", "", -1, false));
	dboSession.add(new Dbo::Language("xh", "Xhosa", "", "xh*", "", -1, false));
	dboSession.add(new Dbo::Language("yi", "Yiddish", "", "yi*", "", -1, false));
	dboSession.add(new Dbo::Language("yo", "Yoruba", "", "yo*", "", -1, false));
	dboSession.add(new Dbo::Language("za", "Zhuang, Chuang", "", "za*", "", -1, false));
	dboSession.add(new Dbo::Language("zu", "Zulu", "", "zu*", "", -1, false));
}

	}
}
