#include "DboInstaller/DboInstaller.h"

void DboInstaller::InsertLanguages()
{
	//English
	O.EnglishLanguagePtr = DboSession.add(new Language("en"));
	O.EnglishLanguagePtr.modify()->Name = "English";
	O.EnglishLanguagePtr.modify()->NativeName = "English";
	O.EnglishLanguagePtr.modify()->LanguageAccept = "en*";
	O.EnglishLanguagePtr.modify()->PluralExpression = "n > 1 ? 1 : 0"; //Case 0 for Singular string and Case 1 for Plural string
	O.EnglishLanguagePtr.modify()->PluralCases = 2;
	O.EnglishLanguagePtr.modify()->Installed = true;

	//Uninstalled languages
	Wt::Dbo::ptr<Language> abLanguagePtr = DboSession.add(new Language("ab", "Abkhaz", "", "ab*", "", -1, false));
	Wt::Dbo::ptr<Language> aaLanguagePtr = DboSession.add(new Language("aa", "Afar", "", "aa*", "", -1, false));
	Wt::Dbo::ptr<Language> afLanguagePtr = DboSession.add(new Language("af", "Afrikaans", "", "af*", "", -1, false));
	Wt::Dbo::ptr<Language> akLanguagePtr = DboSession.add(new Language("ak", "Akan", "", "ak*", "", -1, false));
	Wt::Dbo::ptr<Language> sqLanguagePtr = DboSession.add(new Language("sq", "Albanian", "", "sq*", "", -1, false));
	Wt::Dbo::ptr<Language> amLanguagePtr = DboSession.add(new Language("am", "Amharic", "", "am*", "", -1, false));
	Wt::Dbo::ptr<Language> arLanguagePtr = DboSession.add(new Language("ar", "Arabic", "", "ar*", "", -1, false));
	Wt::Dbo::ptr<Language> anLanguagePtr = DboSession.add(new Language("an", "Aragonese", "", "an*", "", -1, false));
	Wt::Dbo::ptr<Language> hyLanguagePtr = DboSession.add(new Language("hy", "Armenian", "", "hy*", "", -1, false));
	Wt::Dbo::ptr<Language> asLanguagePtr = DboSession.add(new Language("as", "Assamese", "", "as*", "", -1, false));
	Wt::Dbo::ptr<Language> avLanguagePtr = DboSession.add(new Language("av", "Avaric", "", "av*", "", -1, false));
	Wt::Dbo::ptr<Language> aeLanguagePtr = DboSession.add(new Language("ae", "Avestan", "", "ae*", "", -1, false));
	Wt::Dbo::ptr<Language> ayLanguagePtr = DboSession.add(new Language("ay", "Aymara", "", "ay*", "", -1, false));
	Wt::Dbo::ptr<Language> azLanguagePtr = DboSession.add(new Language("az", "Azerbaijani", "", "az*", "", -1, false));
	Wt::Dbo::ptr<Language> bmLanguagePtr = DboSession.add(new Language("bm", "Bambara", "", "bm*", "", -1, false));
	Wt::Dbo::ptr<Language> baLanguagePtr = DboSession.add(new Language("ba", "Bashkir", "", "ba*", "", -1, false));
	Wt::Dbo::ptr<Language> euLanguagePtr = DboSession.add(new Language("eu", "Basque", "", "eu*", "", -1, false));
	Wt::Dbo::ptr<Language> beLanguagePtr = DboSession.add(new Language("be", "Belarusian", "", "be*", "", -1, false));
	Wt::Dbo::ptr<Language> bnLanguagePtr = DboSession.add(new Language("bn", "Bengali; Bangla", "", "bn*", "", -1, false));
	Wt::Dbo::ptr<Language> bhLanguagePtr = DboSession.add(new Language("bh", "Bihari", "", "bh*", "", -1, false));
	Wt::Dbo::ptr<Language> biLanguagePtr = DboSession.add(new Language("bi", "Bislama", "", "bi*", "", -1, false));
	Wt::Dbo::ptr<Language> bsLanguagePtr = DboSession.add(new Language("bs", "Bosnian", "", "bs*", "", -1, false));
	Wt::Dbo::ptr<Language> brLanguagePtr = DboSession.add(new Language("br", "Breton", "", "br*", "", -1, false));
	Wt::Dbo::ptr<Language> bgLanguagePtr = DboSession.add(new Language("bg", "Bulgarian", "", "bg*", "", -1, false));
	Wt::Dbo::ptr<Language> myLanguagePtr = DboSession.add(new Language("my", "Burmese", "", "my*", "", -1, false));
	Wt::Dbo::ptr<Language> caLanguagePtr = DboSession.add(new Language("ca", "Catalan; Valencian", "", "ca*", "", -1, false));
	Wt::Dbo::ptr<Language> chLanguagePtr = DboSession.add(new Language("ch", "Chamorro", "", "ch*", "", -1, false));
	Wt::Dbo::ptr<Language> ceLanguagePtr = DboSession.add(new Language("ce", "Chechen", "", "ce*", "", -1, false));
	Wt::Dbo::ptr<Language> nyLanguagePtr = DboSession.add(new Language("ny", "Chichewa; Chewa; Nyanja", "", "ny*", "", -1, false));
	Wt::Dbo::ptr<Language> zhLanguagePtr = DboSession.add(new Language("zh", "Chinese", "", "zh*", "", -1, false));
	Wt::Dbo::ptr<Language> cvLanguagePtr = DboSession.add(new Language("cv", "Chuvash", "", "cv*", "", -1, false));
	Wt::Dbo::ptr<Language> kwLanguagePtr = DboSession.add(new Language("kw", "Cornish", "", "kw*", "", -1, false));
	Wt::Dbo::ptr<Language> coLanguagePtr = DboSession.add(new Language("co", "Corsican", "", "co*", "", -1, false));
	Wt::Dbo::ptr<Language> crLanguagePtr = DboSession.add(new Language("cr", "Cree", "", "cr*", "", -1, false));
	Wt::Dbo::ptr<Language> hrLanguagePtr = DboSession.add(new Language("hr", "Croatian", "", "hr*", "", -1, false));
	Wt::Dbo::ptr<Language> csLanguagePtr = DboSession.add(new Language("cs", "Czech", "", "cs*", "", -1, false));
	Wt::Dbo::ptr<Language> daLanguagePtr = DboSession.add(new Language("da", "Danish", "", "da*", "", -1, false));
	Wt::Dbo::ptr<Language> dvLanguagePtr = DboSession.add(new Language("dv", "Divehi; Dhivehi; Maldivian;", "", "dv*", "", -1, false));
	Wt::Dbo::ptr<Language> nlLanguagePtr = DboSession.add(new Language("nl", "Dutch", "", "nl*", "", -1, false));
	Wt::Dbo::ptr<Language> dzLanguagePtr = DboSession.add(new Language("dz", "Dzongkha", "", "dz*", "", -1, false));
	Wt::Dbo::ptr<Language> eoLanguagePtr = DboSession.add(new Language("eo", "Esperanto", "", "eo*", "", -1, false));
	Wt::Dbo::ptr<Language> etLanguagePtr = DboSession.add(new Language("et", "Estonian", "", "et*", "", -1, false));
	Wt::Dbo::ptr<Language> eeLanguagePtr = DboSession.add(new Language("ee", "Ewe", "", "ee*", "", -1, false));
	Wt::Dbo::ptr<Language> foLanguagePtr = DboSession.add(new Language("fo", "Faroese", "", "fo*", "", -1, false));
	Wt::Dbo::ptr<Language> fjLanguagePtr = DboSession.add(new Language("fj", "Fijian", "", "fj*", "", -1, false));
	Wt::Dbo::ptr<Language> fiLanguagePtr = DboSession.add(new Language("fi", "Finnish", "", "fi*", "", -1, false));
	Wt::Dbo::ptr<Language> frLanguagePtr = DboSession.add(new Language("fr", "French", "", "fr*", "", -1, false));
	Wt::Dbo::ptr<Language> ffLanguagePtr = DboSession.add(new Language("ff", "Fula; Fulah; Pulaar; Pular", "", "ff*", "", -1, false));
	Wt::Dbo::ptr<Language> glLanguagePtr = DboSession.add(new Language("gl", "Galician", "", "gl*", "", -1, false));
	Wt::Dbo::ptr<Language> kaLanguagePtr = DboSession.add(new Language("ka", "Georgian", "", "ka*", "", -1, false));
	Wt::Dbo::ptr<Language> deLanguagePtr = DboSession.add(new Language("de", "German", "", "de*", "", -1, false));
	Wt::Dbo::ptr<Language> elLanguagePtr = DboSession.add(new Language("el", "Greek, Modern", "", "el*", "", -1, false));
	Wt::Dbo::ptr<Language> gnLanguagePtr = DboSession.add(new Language("gn", "Guaraní", "", "gn*", "", -1, false));
	Wt::Dbo::ptr<Language> guLanguagePtr = DboSession.add(new Language("gu", "Gujarati", "", "gu*", "", -1, false));
	Wt::Dbo::ptr<Language> htLanguagePtr = DboSession.add(new Language("ht", "Haitian; Haitian Creole", "", "ht*", "", -1, false));
	Wt::Dbo::ptr<Language> haLanguagePtr = DboSession.add(new Language("ha", "Hausa", "", "ha*", "", -1, false));
	Wt::Dbo::ptr<Language> heLanguagePtr = DboSession.add(new Language("he", "Hebrew (modern)", "", "he*", "", -1, false));
	Wt::Dbo::ptr<Language> hzLanguagePtr = DboSession.add(new Language("hz", "Herero", "", "hz*", "", -1, false));
	Wt::Dbo::ptr<Language> hiLanguagePtr = DboSession.add(new Language("hi", "Hindi", "", "hi*", "", -1, false));
	Wt::Dbo::ptr<Language> hoLanguagePtr = DboSession.add(new Language("ho", "Hiri Motu", "", "ho*", "", -1, false));
	Wt::Dbo::ptr<Language> huLanguagePtr = DboSession.add(new Language("hu", "Hungarian", "", "hu*", "", -1, false));
	Wt::Dbo::ptr<Language> iaLanguagePtr = DboSession.add(new Language("ia", "Interlingua", "", "ia*", "", -1, false));
	Wt::Dbo::ptr<Language> idLanguagePtr = DboSession.add(new Language("id", "Indonesian", "", "id*", "", -1, false));
	Wt::Dbo::ptr<Language> ieLanguagePtr = DboSession.add(new Language("ie", "Interlingue", "", "ie*", "", -1, false));
	Wt::Dbo::ptr<Language> gaLanguagePtr = DboSession.add(new Language("ga", "Irish", "", "ga*", "", -1, false));
	Wt::Dbo::ptr<Language> igLanguagePtr = DboSession.add(new Language("ig", "Igbo", "", "ig*", "", -1, false));
	Wt::Dbo::ptr<Language> ikLanguagePtr = DboSession.add(new Language("ik", "Inupiaq", "", "ik*", "", -1, false));
	Wt::Dbo::ptr<Language> ioLanguagePtr = DboSession.add(new Language("io", "Ido", "", "io*", "", -1, false));
	Wt::Dbo::ptr<Language> isLanguagePtr = DboSession.add(new Language("is", "Icelandic", "", "is*", "", -1, false));
	Wt::Dbo::ptr<Language> itLanguagePtr = DboSession.add(new Language("it", "Italian", "", "it*", "", -1, false));
	Wt::Dbo::ptr<Language> iuLanguagePtr = DboSession.add(new Language("iu", "Inuktitut", "", "iu*", "", -1, false));
	Wt::Dbo::ptr<Language> jaLanguagePtr = DboSession.add(new Language("ja", "Japanese", "", "ja*", "", -1, false));
	Wt::Dbo::ptr<Language> jvLanguagePtr = DboSession.add(new Language("jv", "Javanese", "", "jv*", "", -1, false));
	Wt::Dbo::ptr<Language> klLanguagePtr = DboSession.add(new Language("kl", "Kalaallisut, Greenlandic", "", "kl*", "", -1, false));
	Wt::Dbo::ptr<Language> knLanguagePtr = DboSession.add(new Language("kn", "Kannada", "", "kn*", "", -1, false));
	Wt::Dbo::ptr<Language> krLanguagePtr = DboSession.add(new Language("kr", "Kanuri", "", "kr*", "", -1, false));
	Wt::Dbo::ptr<Language> ksLanguagePtr = DboSession.add(new Language("ks", "Kashmiri", "", "ks*", "", -1, false));
	Wt::Dbo::ptr<Language> kkLanguagePtr = DboSession.add(new Language("kk", "Kazakh", "", "kk*", "", -1, false));
	Wt::Dbo::ptr<Language> kmLanguagePtr = DboSession.add(new Language("km", "Khmer", "", "km*", "", -1, false));
	Wt::Dbo::ptr<Language> kiLanguagePtr = DboSession.add(new Language("ki", "Kikuyu, Gikuyu", "", "ki*", "", -1, false));
	Wt::Dbo::ptr<Language> rwLanguagePtr = DboSession.add(new Language("rw", "Kinyarwanda", "", "rw*", "", -1, false));
	Wt::Dbo::ptr<Language> kyLanguagePtr = DboSession.add(new Language("ky", "Kyrgyz", "", "ky*", "", -1, false));
	Wt::Dbo::ptr<Language> kvLanguagePtr = DboSession.add(new Language("kv", "Komi", "", "kv*", "", -1, false));
	Wt::Dbo::ptr<Language> kgLanguagePtr = DboSession.add(new Language("kg", "Kongo", "", "kg*", "", -1, false));
	Wt::Dbo::ptr<Language> koLanguagePtr = DboSession.add(new Language("ko", "Korean", "", "ko*", "", -1, false));
	Wt::Dbo::ptr<Language> kuLanguagePtr = DboSession.add(new Language("ku", "Kurdish", "", "ku*", "", -1, false));
	Wt::Dbo::ptr<Language> kjLanguagePtr = DboSession.add(new Language("kj", "Kwanyama, Kuanyama", "", "kj*", "", -1, false));
	Wt::Dbo::ptr<Language> laLanguagePtr = DboSession.add(new Language("la", "Latin", "", "la*", "", -1, false));
	Wt::Dbo::ptr<Language> lbLanguagePtr = DboSession.add(new Language("lb", "Luxembourgish, Letzeburgesch", "", "lb*", "", -1, false));
	Wt::Dbo::ptr<Language> lgLanguagePtr = DboSession.add(new Language("lg", "Ganda", "", "lg*", "", -1, false));
	Wt::Dbo::ptr<Language> liLanguagePtr = DboSession.add(new Language("li", "Limburgish, Limburgan, Limburger", "", "li*", "", -1, false));
	Wt::Dbo::ptr<Language> lnLanguagePtr = DboSession.add(new Language("ln", "Lingala", "", "ln*", "", -1, false));
	Wt::Dbo::ptr<Language> loLanguagePtr = DboSession.add(new Language("lo", "Lao", "", "lo*", "", -1, false));
	Wt::Dbo::ptr<Language> ltLanguagePtr = DboSession.add(new Language("lt", "Lithuanian", "", "lt*", "", -1, false));
	Wt::Dbo::ptr<Language> luLanguagePtr = DboSession.add(new Language("lu", "Luba-Katanga", "", "lu*", "", -1, false));
	Wt::Dbo::ptr<Language> lvLanguagePtr = DboSession.add(new Language("lv", "Latvian", "", "lv*", "", -1, false));
	Wt::Dbo::ptr<Language> gvLanguagePtr = DboSession.add(new Language("gv", "Manx", "", "gv*", "", -1, false));
	Wt::Dbo::ptr<Language> mkLanguagePtr = DboSession.add(new Language("mk", "Macedonian", "", "mk*", "", -1, false));
	Wt::Dbo::ptr<Language> mgLanguagePtr = DboSession.add(new Language("mg", "Malagasy", "", "mg*", "", -1, false));
	Wt::Dbo::ptr<Language> msLanguagePtr = DboSession.add(new Language("ms", "Malay", "", "ms*", "", -1, false));
	Wt::Dbo::ptr<Language> mlLanguagePtr = DboSession.add(new Language("ml", "Malayalam", "", "ml*", "", -1, false));
	Wt::Dbo::ptr<Language> mtLanguagePtr = DboSession.add(new Language("mt", "Maltese", "", "mt*", "", -1, false));
	Wt::Dbo::ptr<Language> miLanguagePtr = DboSession.add(new Language("mi", "Maori", "", "mi*", "", -1, false));
	Wt::Dbo::ptr<Language> mrLanguagePtr = DboSession.add(new Language("mr", "Marathi", "", "mr*", "", -1, false));
	Wt::Dbo::ptr<Language> mhLanguagePtr = DboSession.add(new Language("mh", "Marshallese", "", "mh*", "", -1, false));
	Wt::Dbo::ptr<Language> mnLanguagePtr = DboSession.add(new Language("mn", "Mongolian", "", "mn*", "", -1, false));
	Wt::Dbo::ptr<Language> naLanguagePtr = DboSession.add(new Language("na", "Nauru", "", "na*", "", -1, false));
	Wt::Dbo::ptr<Language> nvLanguagePtr = DboSession.add(new Language("nv", "Navajo, Navaho", "", "nv*", "", -1, false));
	Wt::Dbo::ptr<Language> nbLanguagePtr = DboSession.add(new Language("nb", "Norwegian Bokmål", "", "nb*", "", -1, false));
	Wt::Dbo::ptr<Language> ndLanguagePtr = DboSession.add(new Language("nd", "North Ndebele", "", "nd*", "", -1, false));
	Wt::Dbo::ptr<Language> neLanguagePtr = DboSession.add(new Language("ne", "Nepali", "", "ne*", "", -1, false));
	Wt::Dbo::ptr<Language> ngLanguagePtr = DboSession.add(new Language("ng", "Ndonga", "", "ng*", "", -1, false));
	Wt::Dbo::ptr<Language> nnLanguagePtr = DboSession.add(new Language("nn", "Norwegian Nynorsk", "", "nn*", "", -1, false));
	Wt::Dbo::ptr<Language> noLanguagePtr = DboSession.add(new Language("no", "Norwegian", "", "no*", "", -1, false));
	Wt::Dbo::ptr<Language> iiLanguagePtr = DboSession.add(new Language("ii", "Nuosu", "", "ii*", "", -1, false));
	Wt::Dbo::ptr<Language> nrLanguagePtr = DboSession.add(new Language("nr", "South Ndebele", "", "nr*", "", -1, false));
	Wt::Dbo::ptr<Language> ocLanguagePtr = DboSession.add(new Language("oc", "Occitan", "", "oc*", "", -1, false));
	Wt::Dbo::ptr<Language> ojLanguagePtr = DboSession.add(new Language("oj", "Ojibwe, Ojibwa", "", "oj*", "", -1, false));
	Wt::Dbo::ptr<Language> cuLanguagePtr = DboSession.add(new Language("cu", "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic", "", "cu*", "", -1, false));
	Wt::Dbo::ptr<Language> omLanguagePtr = DboSession.add(new Language("om", "Oromo", "", "om*", "", -1, false));
	Wt::Dbo::ptr<Language> orLanguagePtr = DboSession.add(new Language("or", "Oriya", "", "or*", "", -1, false));
	Wt::Dbo::ptr<Language> osLanguagePtr = DboSession.add(new Language("os", "Ossetian, Ossetic", "", "os*", "", -1, false));
	Wt::Dbo::ptr<Language> paLanguagePtr = DboSession.add(new Language("pa", "Panjabi, Punjabi", "", "pa*", "", -1, false));
	Wt::Dbo::ptr<Language> piLanguagePtr = DboSession.add(new Language("pi", "Pali", "", "pi*", "", -1, false));
	Wt::Dbo::ptr<Language> faLanguagePtr = DboSession.add(new Language("fa", "Persian (Farsi)", "", "fa*", "", -1, false));
	Wt::Dbo::ptr<Language> plLanguagePtr = DboSession.add(new Language("pl", "Polish", "", "pl*", "", -1, false));
	Wt::Dbo::ptr<Language> psLanguagePtr = DboSession.add(new Language("ps", "Pashto, Pushto", "", "ps*", "", -1, false));
	Wt::Dbo::ptr<Language> ptLanguagePtr = DboSession.add(new Language("pt", "Portuguese", "", "pt*", "", -1, false));
	Wt::Dbo::ptr<Language> quLanguagePtr = DboSession.add(new Language("qu", "Quechua", "", "qu*", "", -1, false));
	Wt::Dbo::ptr<Language> rmLanguagePtr = DboSession.add(new Language("rm", "Romansh", "", "rm*", "", -1, false));
	Wt::Dbo::ptr<Language> rnLanguagePtr = DboSession.add(new Language("rn", "Kirundi", "", "rn*", "", -1, false));
	Wt::Dbo::ptr<Language> roLanguagePtr = DboSession.add(new Language("ro", "Romanian, [])", "", "ro*", "", -1, false));
	Wt::Dbo::ptr<Language> ruLanguagePtr = DboSession.add(new Language("ru", "Russian", "", "ru*", "", -1, false));
	Wt::Dbo::ptr<Language> saLanguagePtr = DboSession.add(new Language("sa", "Sanskrit (Samskrta)", "", "sa*", "", -1, false));
	Wt::Dbo::ptr<Language> scLanguagePtr = DboSession.add(new Language("sc", "Sardinian", "", "sc*", "", -1, false));
	Wt::Dbo::ptr<Language> sdLanguagePtr = DboSession.add(new Language("sd", "Sindhi", "", "sd*", "", -1, false));
	Wt::Dbo::ptr<Language> seLanguagePtr = DboSession.add(new Language("se", "Northern Sami", "", "se*", "", -1, false));
	Wt::Dbo::ptr<Language> smLanguagePtr = DboSession.add(new Language("sm", "Samoan", "", "sm*", "", -1, false));
	Wt::Dbo::ptr<Language> sgLanguagePtr = DboSession.add(new Language("sg", "Sango", "", "sg*", "", -1, false));
	Wt::Dbo::ptr<Language> srLanguagePtr = DboSession.add(new Language("sr", "Serbian", "", "sr*", "", -1, false));
	Wt::Dbo::ptr<Language> gdLanguagePtr = DboSession.add(new Language("gd", "Scottish Gaelic; Gaelic", "", "gd*", "", -1, false));
	Wt::Dbo::ptr<Language> snLanguagePtr = DboSession.add(new Language("sn", "Shona", "", "sn*", "", -1, false));
	Wt::Dbo::ptr<Language> siLanguagePtr = DboSession.add(new Language("si", "Sinhala, Sinhalese", "", "si*", "", -1, false));
	Wt::Dbo::ptr<Language> skLanguagePtr = DboSession.add(new Language("sk", "Slovak", "", "sk*", "", -1, false));
	Wt::Dbo::ptr<Language> slLanguagePtr = DboSession.add(new Language("sl", "Slovene", "", "sl*", "", -1, false));
	Wt::Dbo::ptr<Language> soLanguagePtr = DboSession.add(new Language("so", "Somali", "", "so*", "", -1, false));
	Wt::Dbo::ptr<Language> stLanguagePtr = DboSession.add(new Language("st", "Southern Sotho", "", "st*", "", -1, false));
	Wt::Dbo::ptr<Language> esLanguagePtr = DboSession.add(new Language("es", "Spanish; Castilian", "", "es*", "", -1, false));
	Wt::Dbo::ptr<Language> suLanguagePtr = DboSession.add(new Language("su", "Sundanese", "", "su*", "", -1, false));
	Wt::Dbo::ptr<Language> swLanguagePtr = DboSession.add(new Language("sw", "Swahili", "", "sw*", "", -1, false));
	Wt::Dbo::ptr<Language> ssLanguagePtr = DboSession.add(new Language("ss", "Swati", "", "ss*", "", -1, false));
	Wt::Dbo::ptr<Language> svLanguagePtr = DboSession.add(new Language("sv", "Swedish", "", "sv*", "", -1, false));
	Wt::Dbo::ptr<Language> taLanguagePtr = DboSession.add(new Language("ta", "Tamil", "", "ta*", "", -1, false));
	Wt::Dbo::ptr<Language> teLanguagePtr = DboSession.add(new Language("te", "Telugu", "", "te*", "", -1, false));
	Wt::Dbo::ptr<Language> tgLanguagePtr = DboSession.add(new Language("tg", "Tajik", "", "tg*", "", -1, false));
	Wt::Dbo::ptr<Language> thLanguagePtr = DboSession.add(new Language("th", "Thai", "", "th*", "", -1, false));
	Wt::Dbo::ptr<Language> tiLanguagePtr = DboSession.add(new Language("ti", "Tigrinya", "", "ti*", "", -1, false));
	Wt::Dbo::ptr<Language> boLanguagePtr = DboSession.add(new Language("bo", "Tibetan Standard, Tibetan, Central", "", "bo*", "", -1, false));
	Wt::Dbo::ptr<Language> tkLanguagePtr = DboSession.add(new Language("tk", "Turkmen", "", "tk*", "", -1, false));
	Wt::Dbo::ptr<Language> tlLanguagePtr = DboSession.add(new Language("tl", "Tagalog", "", "tl*", "", -1, false));
	Wt::Dbo::ptr<Language> tnLanguagePtr = DboSession.add(new Language("tn", "Tswana", "", "tn*", "", -1, false));
	Wt::Dbo::ptr<Language> toLanguagePtr = DboSession.add(new Language("to", "Tonga (Tonga Islands)", "", "to*", "", -1, false));
	Wt::Dbo::ptr<Language> trLanguagePtr = DboSession.add(new Language("tr", "Turkish", "", "tr*", "", -1, false));
	Wt::Dbo::ptr<Language> tsLanguagePtr = DboSession.add(new Language("ts", "Tsonga", "", "ts*", "", -1, false));
	Wt::Dbo::ptr<Language> ttLanguagePtr = DboSession.add(new Language("tt", "Tatar", "", "tt*", "", -1, false));
	Wt::Dbo::ptr<Language> twLanguagePtr = DboSession.add(new Language("tw", "Twi", "", "tw*", "", -1, false));
	Wt::Dbo::ptr<Language> tyLanguagePtr = DboSession.add(new Language("ty", "Tahitian", "", "ty*", "", -1, false));
	Wt::Dbo::ptr<Language> ugLanguagePtr = DboSession.add(new Language("ug", "Uyghur, Uighur", "", "ug*", "", -1, false));
	Wt::Dbo::ptr<Language> ukLanguagePtr = DboSession.add(new Language("uk", "Ukrainian", "", "uk*", "", -1, false));
	Wt::Dbo::ptr<Language> urLanguagePtr = DboSession.add(new Language("ur", "Urdu", "", "ur*", "", -1, false));
	Wt::Dbo::ptr<Language> uzLanguagePtr = DboSession.add(new Language("uz", "Uzbek", "", "uz*", "", -1, false));
	Wt::Dbo::ptr<Language> veLanguagePtr = DboSession.add(new Language("ve", "Venda", "", "ve*", "", -1, false));
	Wt::Dbo::ptr<Language> viLanguagePtr = DboSession.add(new Language("vi", "Vietnamese", "", "vi*", "", -1, false));
	Wt::Dbo::ptr<Language> voLanguagePtr = DboSession.add(new Language("vo", "Volapük", "", "vo*", "", -1, false));
	Wt::Dbo::ptr<Language> waLanguagePtr = DboSession.add(new Language("wa", "Walloon", "", "wa*", "", -1, false));
	Wt::Dbo::ptr<Language> cyLanguagePtr = DboSession.add(new Language("cy", "Welsh", "", "cy*", "", -1, false));
	Wt::Dbo::ptr<Language> woLanguagePtr = DboSession.add(new Language("wo", "Wolof", "", "wo*", "", -1, false));
	Wt::Dbo::ptr<Language> fyLanguagePtr = DboSession.add(new Language("fy", "Western Frisian", "", "fy*", "", -1, false));
	Wt::Dbo::ptr<Language> xhLanguagePtr = DboSession.add(new Language("xh", "Xhosa", "", "xh*", "", -1, false));
	Wt::Dbo::ptr<Language> yiLanguagePtr = DboSession.add(new Language("yi", "Yiddish", "", "yi*", "", -1, false));
	Wt::Dbo::ptr<Language> yoLanguagePtr = DboSession.add(new Language("yo", "Yoruba", "", "yo*", "", -1, false));
	Wt::Dbo::ptr<Language> zaLanguagePtr = DboSession.add(new Language("za", "Zhuang, Chuang", "", "za*", "", -1, false));
	Wt::Dbo::ptr<Language> zuLanguagePtr = DboSession.add(new Language("zu", "Zulu", "", "zu*", "", -1, false));

	//Basic formatting
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("DecimalPointCharacter", ".", O.LocalizationModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("NumberThousandSeparator", ",", O.LocalizationModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("DateFormat", "MMMM dd, yyyy", O.LocalizationModule)));

	//Wt built in internationalization strings
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WAbstractItemView.PageIOfN", "<b>{1}</b> of <b>{2}</b>", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WAbstractItemView.PageBar.First", "&#x00ab; First", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WAbstractItemView.PageBar.Previous", "&#x2039; Previous", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WAbstractItemView.PageBar.Next", "Next &#x203a;", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WAbstractItemView.PageBar.Last", "Last &#x00bb;", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WCalendar.PrevMonth", "&#x00ab;", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WCalendar.NextMonth", "&#x00bb;", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.Monday", "Monday", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.Tuesday", "Tuesday", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.Wednesday", "Wednesday", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.Thursday", "Thursday", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.Friday", "Friday", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.Saturday", "Saturday", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.Sunday", "Sunday", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Mon", "Mon", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Tue", "Tue", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Wed", "Wed", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Thu", "Thu", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Fri", "Fri", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Sat", "Sat", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Sun", "Sun", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.January", "January", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.February", "February", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.March", "March", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.April", "April", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.May", "May", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.June", "June", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.July", "July", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.August", "August", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.September", "September", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.October", "October", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.November", "November", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.December", "December", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Jan", "Jan", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Feb", "Feb", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Mar", "Mar", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Apr", "Apr", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.May", "May", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Jun", "Jun", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Jul", "Jul", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Aug", "Aug", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Sep", "Sep", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Oct", "Oct", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Nov", "Nov", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDate.3.Dec", "Dec", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDatePicker.Close", "Close", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.LessThanASecond", "less than a second", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.second", "one second", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.seconds", "{1} seconds", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.minute", "one minute", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.minutes", "{1} minutes", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.hour", "one hour", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.hours", "{1} hours", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.day", "one day", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.days", "{1} days", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.week", "one week", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.weeks", "{1} weeks", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.month", "one month", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.months", "{1} months", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.year", "one year", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.years", "{1} years", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateTime.null", "Null", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateValidator.DateTooEarly", "The date must be after {1}", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateValidator.DateTooLate", "The date must be before {1}", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateValidator.WrongDateRange", "The date must be between {1} and {2}", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDateValidator.WrongFormat", "Must be a date in the format '{1}'", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDefaultLoadingIndicator.Loading", "Loading...", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDoubleValidator.NotANumber", "Must be a number", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDoubleValidator.TooSmall", "The number must be larger than {1}", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDoubleValidator.BadRange", "The number must be in the range {1} to {2}", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WDoubleValidator.TooLarge", "The number must be smaller than {1}", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WInPlaceEdit.Save", "Save", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WInPlaceEdit.Cancel", "Cancel", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WIntValidator.NotAnInteger", "Must be an integer number", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WIntValidator.TooSmall", "The number must be larger than {1}", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WIntValidator.BadRange", "The number must be in the range {1} to {2}", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WIntValidator.TooLarge", "The number must be smaller than {1}", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WLengthValidator.TooShort", "The input must be at least {1} characters", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WLengthValidator.BadRange", "The input must have a length between {1} and {2} characters", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WLengthValidator.TooLong", "The input must be no more than {1} characters", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.play", "Play", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.pause", "Pause", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.stop", "Stop", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.mute", "Mute", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.unmute", "Unmute", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.volume-max", "Maximum volume", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.repeat", "Repeat", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.repeat-off", "Repeat off", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.video-play-icon", "Play", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.full-screen", "Full screen", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMediaPlayer.restore-screen", "Restore screen", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMessageBox.Abort", "Abort", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMessageBox.Cancel", "Cancel", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMessageBox.Ignore", "Ignore", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMessageBox.No", "No", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMessageBox.NoToAll", "No to All", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMessageBox.Ok", "Ok", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMessageBox.Retry", "Retry", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMessageBox.Yes", "Yes", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WMessageBox.YesToAll", "Yes to All", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WOverlayLoadingIndicator.Loading", "Loading...", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WRegExpValidator.Invalid", "Invalid input", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.WValidator.Invalid", "This field cannot be empty", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.true", "true", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.false", "false", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.error-invalid-token", "The operation could not be completed: invalid token.", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.error-token-expired", "The operation could not be completed: the token has expired.", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.mail-sent", "An email has been sent. Follow the instructions to set a new password.", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.info-email-confirmed", "Your email address is now confirmed.", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwdqc.reason-error", "Check failed", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwdqc.reason-same", "The same as the old one", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwdqc.reason-similar", "Based on the old one", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwdqc.reason-short", "Too short", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwdqc.reason-long", "Too long", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwdqc.reason-simpleshort", "Not enough different characters or classes for this length", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwdqc.reason-simple", "Not enough different characters or classes", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwdqc.reason-personal", "Based on personal information", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwdqc.reason-word", "Based on a dictionary word and not a passphrase", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwdqc.reason-seq", "Based on a common sequence of characters", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.GoogleService.badresponse", "<p>Sorry, could not login using your Google account.</p><small><p>Google's identification server generated an unexpected response.</p></small>", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.FacebookService.badresponse", "<p>Sorry, could not login using your Facebook account.</p><small><p>Facebook's identification server generated an unexpected response.</p></small>", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.login-form-title", "Login", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.user-name", "User name", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.user-name-info", "Enter your user name", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.user-name-invalid", "Invalid", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.email", "Email address", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.email-info", "Enter your email address", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.optional-email-info", "Enter your email address (optional)", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.password", "Password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.password-info", "Enter your password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.remember-me", "Remember me", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.remember-me-info.days", "Keeps login for {1} days", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.remember-me-info.weeks", "Keeps login for {1} weeks", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.lost-password", "Lost password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.login", "Login", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.logout", "Logout", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.throttle-retry", "Retry in {1}s", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.registration-form-title", "Registration", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.registration-form-info", "Please complete the following information to register.", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.password-or-oauth-registration", "<h3>Register using a user name and password:</h3>", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.oauth-registration", "<h3>Register with an identity provider:</h3>", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.or-oauth-registration", "<h3>Or, register with an identity provider:</h3>", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.valid", "Valid", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.choose-password", "Password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.choose-password-info", "Choose a password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.repeat-password", "Repeat password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.repeat-password-info", "Re-enter your password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.email-invalid", "Invalid email address", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.email-exists", "Email already registered", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.oauth", "Your account", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.oauth-info", "Choose one of your accounts", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.user-name-exists", "User already exists", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.confirm-is-you", "User exists, is this you?", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.user-name-tooshort", "Min. size {1} characters", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.password-tooshort", "Min. size {1} characters", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.passwords-dont-match", "Passwords don't match", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.registration", "Registration", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.register", "Register", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.error-user-invalid", "Registration failed.", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.enter-password", "Enter your password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.password-prompt-form-title", "Enter your password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.password-invalid", "Invalid password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.updatepassword", "Update password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.update-password-form-title", "Update password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.update-password-form-info", "Enter a new password below", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.old-password", "Current password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.old-password-info", "Enter your current password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.new-password", "New password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.repeat-new-password", "Repeat new password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.repeat-new-password-info", "Re-enter your new password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.lostpassword", "Password forgotten? No sweat!", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.lost-password-form-title", "Recover your password", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.lost-password-form-info", "Please enter below the email address which you used during registration. A mail will be sent with instructions to enter a new password.", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.send", "Send", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.error", "Error", O.WtModule)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.notice", "Notice", O.WtModule)));

	//Emails
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.confirmmail.subject", "User account activation Link", O.WtModule, Wt::Dbo::ptr<Language>(), true)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.confirmmail.body", "Hello {1},\r\n\r\nThank you for joining!\r\n\r\nTo complete your registration, please finally confirm your account by clicking on the following link or copying the URL into your browser.\r\n \r\nPlease click here to confirm your registration or copy and paste the following URL into your browser: (Note: be sure to copy the entire URL, including any part of it which goes onto a second line.)\r\n\r\n{3}", O.WtModule, Wt::Dbo::ptr<Language>(), true)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.confirmmail.htmlbody", "<h3>Hello {1},</h3>\r\n\r\n<p>Thank you for joining!</p>\r\n\r\n<p>To complete your registration, please finally confirm your account by clicking on the following link or copying the URL into your browser.</p>\r\n \r\n<p>Please <a href=\"{3}\">click here to confirm</a> your registration or copy and paste the following URL into your browser: <i>(Note: be sure to copy the entire URL, including any part of it which goes onto a second line.)</i></p>\r\n\r\n<b>{3}</b>", O.WtModule, Wt::Dbo::ptr<Language>(), true)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.lostpasswordmail.subject", "Lost password instructions", O.WtModule, Wt::Dbo::ptr<Language>(), true)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.lostpasswordmail.body", "Hello {1},\r\n\r\nThis mail has been sent to you, because someone (presumably you?) indicated that he wishes to choose a new password, because the current password escapes his mind.\r\n\r\nIf you requested this, then choose a new password by clicking on the following link or copying the URL into your browser. If you didn't request this, you can safely ignore and discard this email.\r\n \r\nPlease copy and paste the following URL into your browser: (Note: be sure to copy the entire URL, including any part of it which goes onto a second line.)\r\n \r\n{3}", O.WtModule, Wt::Dbo::ptr<Language>(), true)));
	O.EnglishLanguagePtr.modify()->LanguageSingleCollection.insert(DboSession.add(new LanguageSingle("Wt.Auth.lostpasswordmail.htmlbody", "<h3>Hello {1},</h3>\r\n\r\n<p>This mail has been sent to you, because someone (presumably you?)  indicated that he wishes to choose a new password, because the current password escapes his mind.</p>\r\n\r\n<p>If you requested this, then choose a new password by clicking on the following link or copying the URL into your browser. If you didn't request this, you can safely ignore and discard this email.</p>\r\n \r\n<p>Please <a href=\"{3}\">click here to choose a new password</a> or copy and paste the following URL into your browser: <i>(Note: be sure to copy the entire URL, including any part of it which goes onto a second line.)</i></p>\r\n\r\n<b>{3}</b>", O.WtModule, Wt::Dbo::ptr<Language>(), true)));
}
